# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: On Release
on:
  release:
    types:
      - published
jobs:
  lint:
    name: Lint
    permissions:
      # -- To clone repository
      contents: read
    uses: ./.github/workflows/lint.yaml
    with:
      ref: ${{github.event.release.tag_name}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  dependency-submission:
    name: Dependency Submission
    permissions:
      # -- Needed to clone the repository and submit dependency reports
      contents: write
    uses: ./.github/workflows/dependency-submission.yaml
    with:
      ref: ${{github.sha}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
  release:
    name: Publish
    permissions:
      # -- To clone repository write release artifacts
      contents: write
    needs:
      - lint
      - dependency-submission
    uses: ./.github/workflows/publish.yaml
    with:
      ref: ${{github.event.release.tag_name}}
      github-release-id: ${{github.event.release.id}}
      attach-to-github-release: true
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
