# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish
on:
  workflow_call:
    inputs:
      github-release-id:
        description: |
          The GitHub release ID to attach the artifacts to.

          Must be the value used in "databaseId" for the release to attach
          assets to.

          Only required when "attach-to-github-release" is "true".
        type: string
        required: false
        default: ''
      attach-to-github-release:
        description: |
          Whether to attach the released assets to a GitHub release.

          Useful when testing other parts of the publish workflow.

          Defaults to "true".
        type: boolean
        required: false
        default: true
      ref:
        description: |
          The Git reference from which to clone the project.

          This can be any valid Git commit-ish (e.g. a SHA, a ref, a tag, and so
          on).

          Defaults to the SHA that caused the workflow to be triggered. If that
          is unavailable the fully formed reference of the branch or tag that
          triggered the workflow is used. If that is unavailable the repository
          default branch is used.
        type: string
        required: false
        default: ${{github.sha || github.ref || github.event.repository.default_branch}}
      java-vendor:
        description: |
          The Java vendor to use.

          Defaults to "temurin".
        type: string
        required: false
        default: temurin
      java-version:
        description: |
          The Java version to use.

          Defaults to "version-file" to use the version found in the
          ".java-version" file present in the project.
        type: string
        required: false
        default: version-file
      gradle-version:
        description: |
          The Gradle version to use.

          Defaults to "wrapper" to use version of the Gradle wrapper present in
          the project.
        type: string
        required: false
        default: wrapper
    secrets:
      github-token:
        description: |
          The token to use when making authenticated calls to the GitHub API.
        required: true
jobs:
  build:
    name: Build
    permissions:
      # -- To clone repository
      contents: read
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{inputs.ref}}
      java-version: ${{inputs.java-version}}
      java-vendor: ${{inputs.java-vendor}}
      gradle-version: ${{inputs.gradle-version}}
    secrets:
      github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      # -- To clone repository and write release artifacts
      contents: write
    needs:
      - build
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true
          submodules: recursive
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: download-artifacts
        name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          artifact-ids: ${{needs.build.outputs.artifact-id}}
          path: artifacts
      - id: generate-checksums
        name: Generate checksums
        run: |
          md5sum ${{steps.download-artifacts.outputs.download-path}}/* > checksums_md5.txt
          shasum -a 1 ${{steps.download-artifacts.outputs.download-path}}/* > checksums_sha1.txt
          shasum -a 256 ${{steps.download-artifacts.outputs.download-path}}/* > checksums_sha256.txt
          mv *.txt ${{steps.download-artifacts.outputs.download-path}}/
      - id: attach-to-release
        name: Attach artifacts to release
        uses: actions/github-script@v8
        if: inputs.attach-to-github-release
        with:
          script: |
            const script = require('./.github/scripts/upload-release-assets.js');
            await script({github, context, core}, ${{toJson(steps.download-artifacts.outputs.download-path)}}, ${{toJson(inputs.github-release-id)}});
